# https://docs.docker.com/compose/how-tos/multiple-compose-files/include/

include:
  - path:
      - modules/backend/docker/production.yml
      - override/backend.yml
  - path:
      - modules/frontend/docker/production.yml
      - override/frontend.yml
  - path:
      - modules/proxy/docker/production.yml
      - override/proxy.yml
